/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dem040' at '27/05/16 4:48 PM' with Gradle 2.7
 *
 * @author dem040, @date 27/05/16 4:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
